name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -B build -S .
    - name: make
      run: make -C build
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files:
          - build/pico-guitar-midi-tracker.uf2

